theme: jekyll-theme-minimal

favicon:
  small: /img/MaiweiAI.ico
  #medium: /images/favicon-32x32-next.png
  medium: /img/MaiweiAI.ico
  apple_touch_icon: /img/MaiweiAI.ico
  safari_pinned_tab: /img/MaiweiAI.ico
  #android_manifest: /manifest.json
  title: Maiwei AI Lab 

<link rel="shortcut icon" type="image/x-icon" href="./img/MaiweiAI.ico" media="screen" />
